---
- name: nexus - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ nexus_configuration_directory }}"
    - "{{ nexus_docker_compose_directory }}"

- name: nexus - copy docker-compose.yml file
  template:
    src: nexus/docker-compose.yml.j2
    dest: "{{ nexus_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: nexus - pull images
  command: "docker-compose -f {{ nexus_docker_compose_directory }}/docker-compose.yml pull"
  register: result
  changed_when: ('Downloaded' in result.stdout)

- name: nexus - run service
  command: "docker-compose -f {{ nexus_docker_compose_directory }}/docker-compose.yml up -d --remove-orphans --no-build"
  register: result
  changed_when: ('Creating' in result.stdout or 'Recreating' in result.stdout)
