---
- name: nginx - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0755
  become: true
  with_items:
    - "{{ nginx_configuration_directory }}"
    - "{{ nginx_docker_compose_directory }}"

- name: nginx - copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - src: nginx/nginx.conf.j2
      dest: "{{ nginx_configuration_directory }}/nginx.conf"

- name: nginx - copy docker-compose.yml file
  template:
    src: nginx/docker-compose.yml.j2
    dest: "{{ nginx_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: nginx - pull images
  command: "docker-compose -f {{ nginx_docker_compose_directory }}/docker-compose.yml pull"
  register: result
  changed_when: ('Downloaded' in result.stdout)

- name: nginx - run service
  command: "docker-compose -f {{ nginx_docker_compose_directory }}/docker-compose.yml up -d --remove-orphans --no-build"
  register: result
  changed_when: ('Creating' in result.stdout or 'Recreating' in result.stdout)
