---
- name: registry - gather the apt package facts
  package_facts:
    manager: auto

- name: registry - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ registry_configuration_directory }}"
    - "{{ registry_docker_compose_directory }}"

- name: registry - copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - src: registry/registry.yml.j2
      dest: "{{ registry_configuration_directory }}/config.yml"

- name: registry - copy docker-compose.yml file
  template:
    src: registry/docker-compose.yml.j2
    dest: "{{ registry_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: registry - run service
  docker_compose:
    project_src: "{{ registry_docker_compose_directory }}"
    build: false
    pull: true
    remove_orphans: true
  when: "'docker-compose' in ansible_facts.packages"

# NOTE: If docker-compose was not installed by package, the Python bindings are not available.
#       Therefore in this case docker-compose is called directly.

- name: registry - pull images
  command: "docker-compose -f {{ registry_docker_compose_directory }}/docker-compose.yml pull"
  register: result
  changed_when: ('Downloaded' in result.stdout)
  when: "'docker-compose' not in ansible_facts.packages"

- name: registry - run service
  command: "docker-compose -f {{ registry_docker_compose_directory }}/docker-compose.yml up -d --remove-orphans --no-build"
  register: result
  changed_when: ('Creating' in result.stdout or 'Recreating' in result.stdout)
  when: "'docker-compose' not in ansible_facts.packages"
