---
- name: registry - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ registry_configuration_directory }}"

- name: registry - copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  with_items:
    - src: registry/registry.yml.j2
      dest: "{{ registry_configuration_directory }}/config.yml"

- name: registry - copy docker-compose.yml file
  template:
    src: registry/docker-compose.yml.j2
    dest: "{{ registry_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: registry - pull images
  command: "docker-compose -f {{ registry_docker_compose_directory }}/docker-compose.yml pull"
  register: result
  changed_when: ('Downloaded' in result.stdout)

- name: registry - run service
  command: "docker-compose -f {{ registry_docker_compose_directory }}/docker-compose.yml up -d --remove-orphans --no-build"
  register: result
  changed_when: ('Creating' in result.stdout or 'Recreating' in result.stdout)
