---
- name: Playbook for role testing
  hosts: all
  connection: paramiko

  vars:
    ansible_ssh_user: dragon

    configure_aptly: yes
    configure_nexus: yes
    configure_registry: yes

    nexus_registry_port: 5001

  roles:
    - role: ansible-mirror
